#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login:
    path: /login
    methods: [POST]

contact:
    path: /contact
    controller: App\Action\Contact
    methods: [POST]
